META_TASK_POLICY: dict[str, dict[str, bool]] = {'sandbox_infra': {'bypass_fuzzer': True, 'skip_structural_decomp': True}, 'mcp_server_change': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'config_schema': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'data_model': {'bypass_fuzzer': True, 'skip_structural_decomp': True}, 'cli_tooling': {'bypass_fuzzer': False, 'skip_structural_decomp': False}, 'test_unit': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'test_integration': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'test_e2e': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'test_acceptance': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'docs_writing': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'refactor': {'bypass_fuzzer': False, 'skip_structural_decomp': False}, 'logging_observability': {'bypass_fuzzer': False, 'skip_structural_decomp': False}, 'orchestration': {'bypass_fuzzer': True, 'skip_structural_decomp': True}, 'harness_plumbing': {'bypass_fuzzer': True, 'skip_structural_decomp': True, 'skip_smoke_gates': True}, 'planner_tooling': {'bypass_fuzzer': True, 'skip_structural_decomp': True}, 'hooks_integration': {'bypass_fuzzer': True, 'skip_structural_decomp': False, 'skip_smoke_gates': True}, 'validation': {'bypass_fuzzer': True, 'skip_structural_decomp': False}, 'mcp_plumbing': {'bypass_fuzzer': True, 'skip_structural_decomp': True}, 'state_machine': {'bypass_fuzzer': True, 'skip_structural_decomp': True}, 'io_adapter': {'bypass_fuzzer': False, 'skip_structural_decomp': True}, 'harness_self_fix': {'bypass_fuzzer': True, 'skip_structural_decomp': True, 'skip_smoke_gates': True}, 'test_authoring': {'bypass_fuzzer': False, 'skip_structural_decomp': True, 'skip_interface_fuzz': True}}
META_TASK_TYPES: frozenset[str] = frozenset(META_TASK_POLICY.keys())
BYPASS_FUZZER_TYPES: frozenset[str] = frozenset((k for k, v in META_TASK_POLICY.items() if v['bypass_fuzzer']))
SIDE_EFFECT_META_TYPES: frozenset[str] = frozenset((k for k, v in META_TASK_POLICY.items() if v['skip_structural_decomp']))
SKIP_SMOKE_GATE_TYPES: frozenset[str] = frozenset((k for k, v in META_TASK_POLICY.items() if v.get('skip_smoke_gates', False)))
META_TASK_TAXONOMY_VERSION = 1

def is_test_prefixed(meta_task_type: str) -> bool:
    if not isinstance(meta_task_type, str):
        return False
    return meta_task_type.startswith('test_')